name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to private registry
      uses: docker/login-action@v1
      with:
        registry: 219.135.230.196:5000
        username: test
        password: test111
              
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        config-inline: |
          [registry."219.135.230.196:5000"]
            http = true
            insecure = true
