name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
            
    - name: Modify Docker daemon.json
      run: |
        echo '{
          "insecure-registries" : ["219.135.230.194:5001"]
        }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        
    - name: Login to private registry
      uses: docker/login-action@v1
      with:
        registry: 219.135.230.194:5001
              

